# #
# # This action will publish Chatwoot CE docker image.
# # This is set to run against merges to develop, master
# # and when tags are created.
# #

name: Deploy Release Image for production
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: twerlo/zafy:latest # ref_name to get tags/branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Strip enterprise code
        run: |
          rm -rf enterprise
          rm -rf spec/enterprise

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }}|docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: docker build --build-arg "CW_EDITION=ce" --build-arg "DOCKER_TAG=${{ env.IMG_NAME }}" -f docker/Dockerfile -t ${{ env.IMG_NAME }} .

      - name: Push image
        run: docker push ${{ env.IMG_NAME }}
